import { EmbedBuilder, SlashCommandBuilder } from 'discord.js';
import { Configuration, OpenAIApi } from "openai";
import dotenv from 'dotenv';
dotenv.config();

export = {
  data: new SlashCommandBuilder()
    .setName('chat')
    .setDescription('chatGPT - Chat with GPT-3'),

  async execute(interaction: any) {

    await interaction.reply("Generating response...");

    const configuration = new Configuration({
      apiKey: process.env.OPENAI_API_KEY,
    });

    const openai = new OpenAIApi(configuration);
    
    const response = await openai.createCompletion({
      model: "text-davinci-003",
      prompt: "What is Postman and how does it work?",
      temperature: 0,
      max_tokens: 3000,
    });

    console.log(response.data)

    

    const msg = new EmbedBuilder()
      .setColor('#c7651a')
      .setTitle('ChatGPT')
      .setDescription(
          response.data.choices[0].text!.toString()
      )
      .addFields(
        {
          name: 'OpeanAI',
          value: "This was generated by GPT-3 OpenAI"
        }
      )
      .setTimestamp();

    await interaction.editReply({ embeds: [msg] });
    
  },
};
