name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi! Thanks for your interest on helping out Postman Student Helper. Our team will review this issue as soon as possible.'
        pr-message: 'Thanks for your contributions. Our team will review this PR as soon as possible.'
